apiVersion: v1
kind: Service
metadata:
  name: hello-webapp
  labels: 
    app: my-webapp
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80    
  selector:
    app: my-webapp
    tier: frontend
